### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by examinedliving** [conwid/GistManager#2]
After downloading it through VS interface, there is no obvious way to add my credentials.  The extension just shows a screen showing "Login to Gist to...".  Searching Google hasn't yielded anything, so I'm left to believe that I am doing something wrong, or there is a bug.  Please let me know.  Thanks

**Comment by conwid** [comment]
That screen has a small button in the top left corner that pops up a window where you can enter your credentials directly through Github.
